name: Deploy HTML File

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy HTML File
        run: |
          mkdir public
          mv index.html public/
          ls -R
        # Optionally, you can add steps to deploy the HTML file to a web server or hosting service.
